### PR TITLE
Create seifollahi

### PR DESCRIPTION
**Pull request by Seifollahy**
blockchains/arbitrum/info/info.json

### CODE REVIEW

**Comment by Seifollahy** [comment]
[0x007EA5C0Ea75a8DF45D288a4debdD5bb633F9e56](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x007EA5C0Ea75a8DF45D288a4debdD5bb633F9e56)

**Comment by Seifollahy** [comment]
[0x009cF7bC57584b7998236eff51b98A168DceA9B0](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x009cF7bC57584b7998236eff51b98A168DceA9B0)

**Comment by Seifollahy** [comment]
blockchains/smartchain/assets/0x00abaA93fAF8fDc4f382135a7A56F9Cf7C3EdD21/info.json

**Comment by Seifollahy** [comment]
[0x00e1656e45f18ec6747F5a8496Fd39B50b38396D](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x00e1656e45f18ec6747F5a8496Fd39B50b38396D)

**Comment by Seifollahy** [comment]
[0x00e7daf0E5FD1F5331c92d09e3C825A8e4Fc6515](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x00e7daf0E5FD1F5331c92d09e3C825A8e4Fc6515)

**Comment by Seifollahy** [comment]
[0x0112e557d400474717056C4e6D40eDD846F38351](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x0112e557d400474717056C4e6D40eDD846F38351)[](https://github.com/trustwallet/assets/commit/49d0b09091930ef1a05574458908a2dfd8db75e6)

**Comment by Seifollahy** [comment]
[0x01413859d321F423054f6A26276325E8085Dd5fc](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x01413859d321F423054f6A26276325E8085Dd5fc)

**Comment by Seifollahy** [comment]
[0x01600Ed07fC7493686ef143D1b92cd5612d50D5b](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x01600Ed07fC7493686ef143D1b92cd5612d50D5b)

**Comment by Seifollahy** [comment]
[0x016CF83732f1468150D87dCC5BdF67730B3934D3](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x016CF83732f1468150D87dCC5BdF67730B3934D3)

**Comment by Seifollahy** [comment]
[0x01921A94e68F8D54F33C5D6f71d6664C35e33269](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x01921A94e68F8D54F33C5D6f71d6664C35e33269)

**Comment by Seifollahy** [comment]
[0x0cD022ddE27169b20895e0e2B2B8A33B25e63579](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x0cD022ddE27169b20895e0e2B2B8A33B25e63579)
[Ever](https://github.com/trustwallet/assets/commit/d9f548fa5c3a59d9accdc3c5989c9536d2cfdd7c)

**Comment by Seifollahy** [comment]
[0x10051147418C42218986CeDD0aDC266441F8a14f](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x10051147418C42218986CeDD0aDC266441F8a14f)

**Comment by Seifollahy** [comment]
[0x147E07976E1ae78287c33aAFAab87760d32E50A5](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x147E07976E1ae78287c33aAFAab87760d32E50A5)
[I](https://github.com/trustwallet/assets/commit/b2355896a7e5a0b73a0dcbdc5668c49ae471c663)

**Comment by Seifollahy** [comment]
[0x6a8Fd46F88dBD7bdC2D536C604f811C63052ce0F](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x6a8Fd46F88dBD7bdC2D536C604f811C63052ce0F)

**Comment by Seifollahy** [comment]
[0x6b23C89196DeB721e6Fd9726E6C76E4810a464bc](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x6b23C89196DeB721e6Fd9726E6C76E4810a464bc)

**Comment by Seifollahy** [comment]
[0x6C9AE5d6746ee1B6bD03310079AA11d8EC409212](https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x6C9AE5d6746ee1B6bD03310079AA11d8EC409212)

**Comment by reusteur73** [comment]
Hello,
Can you please add more details about the request you made.
Thank you

**Pull request closed without merging**
